### ISSUE TITLE
Inquiry about the usage of get_similarity_matrix.py code

### ISSUE THREAD

**Issue by SupAort** [jinyangwu/KGETCDA#3]
Dear Author,
I hope this message finds you well. I recently came across your code repository on GitHub and found the get_similarity_matrix.py file to be of great interest to me. As a novice in this field, I am eager to understand and learn from your code and accompanying research paper.

Having explored the codebase, I have a few specific questions regarding its usage, particularly in relation to the [main.py] and [test.py]files. I would greatly appreciate your guidance and assistance in modifying these files appropriately. Please accept my apologies if these questions seem basic; I am still in the process of familiarizing myself with the tools and concepts employed in this domain.

1、Could you please provide detailed instructions on how to utilize the get_similarity_matrix.py script within the context of the [main.py]file? Are there any specific functions or variables that need to be modified in order to incorporate get_similarity_matrix.py into the main workflow?

2、In the [test.py]file, are there any specific sections or lines of code that require modification in order to effectively use the get_similarity_matrix.py functionality? Additionally, could you kindly outline the recommended approach for integrating the [test.py]script with the main functionality of your code?
I truly appreciate your time and expertise in providing answers to these queries. Your code and research have already been instrumental in expanding my knowledge in this area, and I am eager to delve deeper with your guidance.

Thank you very much for your attention and patience. I look forward to your response.
Kind regards

**Comment by SupAort** [comment]
I get an error when I use my own similar matrix data to run test.py
=========================================
：./trained_model/KGETCDA/Dataset1/embed-dim2048_relation-dim2048_gcn_KGET_512-256-128-64_lr0.0001_heads16_layers1_decodertwomult//MLP_dropout_0.04/MLP_lr_0.0009/MLP_wd_1e-07/MLP_epochs_65/sim_type_fusedNow testing in fold1......
Traceback (most recent call last):
  File "D:/Projects/KGETCDA-main/test.py", line 310, in <module>
    test(args)
  File "D:/Projects/KGETCDA-main/test.py", line 276, in test
    feature_train, label_train = get_train_data(train_index, rel_mat, circ_sim_mat, circ_embed, 
  File "D:/Projects/KGETCDA-main/test.py", line 163, in get_train_data
    associate_dis_set = find_associated_diseases(top_k_circ_list, rel_mat, associate_dis_set)
  File "D:/Projects/KGETCDA-main/test.py", line 144, in find_associated_diseases
    if rel_matrix[circ_id, j] == 1:
IndexError: index 4485 is out of bounds for axis 0 with size 330

**Comment by jinyangwu** [comment]
> Dear Author, I hope this message finds you well. I recently came across your code repository on GitHub and found the get_similarity_matrix.py file to be of great interest to me. As a novice in this field, I am eager to understand and learn from your code and accompanying research paper.
> 
> Having explored the codebase, I have a few specific questions regarding its usage, particularly in relation to the [main.py] and [test.py]files. I would greatly appreciate your guidance and assistance in modifying these files appropriately. Please accept my apologies if these questions seem basic; I am still in the process of familiarizing myself with the tools and concepts employed in this domain.
> 
> 1、Could you please provide detailed instructions on how to utilize the get_similarity_matrix.py script within the context of the [main.py]file? Are there any specific functions or variables that need to be modified in order to incorporate get_similarity_matrix.py into the main workflow?
> 
> 2、In the [test.py]file, are there any specific sections or lines of code that require modification in order to effectively use the get_similarity_matrix.py functionality? Additionally, could you kindly outline the recommended approach for integrating the [test.py]script with the main functionality of your code? I truly appreciate your time and expertise in providing answers to these queries. Your code and research have already been instrumental in expanding my knowledge in this area, and I am eager to delve deeper with your guidance.
> 
> Thank you very much for your attention and patience. I look forward to your response. Kind regards

Hello, thanks for your attention!

As for how to intergrate [main.py] and [test.py] well, we think we have done this before, and you can refer to the last two line code of [main.py](https://github.com/jinyangwu/KGETCDA/blob/main/main.py).

And for the similarity question, we recommend you first generate guassian and functional similarity using the classes in [get_similarity_matrix.py](https://github.com/jinyangwu/KGETCDA/blob/main/utils/get_similarity_matrix.py), and then intergrate them just following the equation (11) and (12) in our paper [KGETCDA: an efficient representation learning framework based on knowledge graph encoder from transformer for predicting circRNA-disease associations](https://academic.oup.com/bib/article-abstract/24/5/bbad292/7242591?redirectedFrom=fulltext&login=false).

Hope this can help you!
